### ISSUE TITLE
acial landmarks from mobile camera 

### ISSUE THREAD

**Issue by sarmadm** [flyingzhao/FacialLandmarkAndroid#1]
HI

is it possible to use your app to detect facial landmarks from mobile camera ?

**Comment by flyingzhao** [comment]
yes, you can. This program just needs a Bitmap, you can get an image from camera as a Bitmap.

**Comment by sarmadm** [comment]
I need to save facial landmark points into a file using mobile camera , can I save these landmarks ?

**Comment by flyingzhao** [comment]
Yes, you can. You just need to get the output from the jni interface. I suggest that you should read the code.
